--- # build server
- hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  pre_tasks:
   - include_vars: group_vars/all
  roles:
   - setmyhostname
   - repos
   - packages
   - create-local-user
